In [2]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

from python1 import X_train

In [4]:
data = {
    'text': [
        'Free money now',
        'Call now to claim your prize',
        'Meet me at the park',
        'Let’s catch up later',
        'Win a new car today!',
        'Lunch plans?',
        'Congratulations! You won a lottery',
        'Can you send me the report?',
        'Exclusive offer for you',
        'Are you coming to the meeting?'
    ],
    'label': ['spam', 'spam', 'not spam', 'not spam', 'spam', 'not spam', 'spam', 'not spam', 'spam', 'not spam']
}

df = pd.DataFrame(data)
df

                                 text     label
0                      Free money now      spam
1        Call now to claim your prize      spam
2                 Meet me at the park  not spam
3                Let’s catch up later  not spam
4                Win a new car today!      spam
5                        Lunch plans?  not spam
6  Congratulations! You won a lottery      spam
7         Can you send me the report?  not spam
8             Exclusive offer for you      spam
9      Are you coming to the meeting?  not spam

3. Mapping Labels to Numerical Values
Next, the labels spam and not spam are converted into numerical values. This step is required because machine learning models work with numerical data.

spam: 1
not spam: 0

In [7]:
df['label'] = df['label'].map({'spam': 1, 'not spam': 0})
df

                                 text  label
0                      Free money now    NaN
1        Call now to claim your prize    NaN
2                 Meet me at the park    NaN
3                Let’s catch up later    NaN
4                Win a new car today!    NaN
5                        Lunch plans?    NaN
6  Congratulations! You won a lottery    NaN
7         Can you send me the report?    NaN
8             Exclusive offer for you    NaN
9      Are you coming to the meeting?    NaN

In [10]:
X=df["text"]
y=df["label"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)